-- ============================================================================
-- FIX WAREHOUSE LOCATION CODES
-- ============================================================================
-- Issue: warehouse_locations has codes like "WH1-R1-RK1" but position codes
-- generated by the frontend use zero-padded format like "WH1-R01-RK01"
--
-- This causes rack lookups to fail in barcodeService.js
--
-- Solution: Update existing codes to use zero-padded format
-- ============================================================================

-- Update WH1 racks to use zero-padded format
UPDATE warehouse_locations
SET code = 'WH1-R01-RK01'
WHERE code = 'WH1-R1-RK1';

UPDATE warehouse_locations
SET code = 'WH1-R02-RK02'
WHERE code = 'WH1-R2-RK2';

UPDATE warehouse_locations
SET code = 'WH1-R03-RK03'
WHERE code = 'WH1-R3-RK3';

UPDATE warehouse_locations
SET code = 'WH1-R04-RK04'
WHERE code = 'WH1-R4-RK4';

UPDATE warehouse_locations
SET code = 'WH1-R05-RK05'
WHERE code = 'WH1-R5-RK5';

UPDATE warehouse_locations
SET code = 'WH1-R06-RK06'
WHERE code = 'WH1-R6-RK6';

UPDATE warehouse_locations
SET code = 'WH1-R07-RK07'
WHERE code = 'WH1-R7-RK7';

-- Verify the update
SELECT 
  id,
  code,
  warehouse_id,
  created_at
FROM warehouse_locations
WHERE warehouse_id IN (SELECT id FROM warehouses WHERE code IN ('WH1', 'WH2'))
ORDER BY code;
